import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { TailwindIndicator } from "@/components/ui/tailwind-indicator";
import { Providers } from "./providers"; // ← add this

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome to Langmate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} h-full overflow-hidden`}>
        <div className="h-full flex flex-col">
          <Header />
          <div className="flex-1 overflow-hidden">
            <Providers>{children}</Providers>
          </div>
        </div>
        <TailwindIndicator />
      </body>
    </html>
  );
}
